Document: vistarter
Title: Debian vistarter Manual
Author: <insert document author here>
Abstract: This manual describes what vistarter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vistarter/vistarter.sgml.gz

Format: postscript
Files: /usr/share/doc/vistarter/vistarter.ps.gz

Format: text
Files: /usr/share/doc/vistarter/vistarter.text.gz

Format: HTML
Index: /usr/share/doc/vistarter/html/index.html
Files: /usr/share/doc/vistarter/html/*.html
